### ISSUE TITLE
Example of how to set MessageTemplate

### ISSUE THREAD

**Issue by andrewgunn** [bytenik/Seq.App.Slack#16]
Could you please provide an example value for `MessageTemplate` in the README.md?

I'm trying to reduce the noise of each error notification sent to Slack, but excluding properties is a step too far. Ideally, I just want to filter out certain properties, which will more than likely mean having a value for `MessageTemplate` that includes the relevant ones.

**Comment by nblumhardt** [comment]
Hi Andrew! If you have a property like `Application` I think you will want something like:

```
[Application] [RenderedMessage]
```

(The template syntax supported by this app is different from the Serilog one.)

Does this help?

**Comment by bronumski** [comment]
I would like to know how to render the slack message using the properties that I want and ignore the ones I don't Ideally formatting them using short fields:

https://api.slack.com/docs/message-attachments
https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22color%22%3A%22danger%22%2C%22title%22%3A%22Some%20error%20occured%22%2C%22text%22%3A%22Error%20summary%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Environment%22%2C%22value%22%3A%22Production%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Applicaton%22%2C%22value%22%3A%22Foo%22%2C%22short%22%3Atrue%7D%5D%7D%5D%7D
![image](https://user-images.githubusercontent.com/3909845/48096951-7a3a8180-e1cd-11e8-9131-1d533ab6f072.png)

**Comment by jglinsek** [comment]
Did anyone ever figure this out? In my dabbling with it, if I put anything in the `Message (optional)` field AND I uncheck the `Exclude Properties` - then all context is lost - I get a standard message with no coloring posted in Slack. I did not dabble with building an entire JSON message with attachments because you'd need logic in there to get the color based on the event level - which doesn't seem feasible?

It would be nice to have an input where you just specify the properties you want (whitelist) as opposed to *exlcuding ALL properties* and leaving it up to the user to figure out how to rebuild the entire message. It seems like we're all just asking to limit the properties that are logged vs. customize the whole message.

**Comment by nblumhardt** [comment]
@jglinsek thanks for chiming in! I don't think there's been progress on this, but looking at it again, would the following simple proposal work?

 * We add a new setting to the `SlackReactor` called `IncludedProperties`; it's a string value
 * If the field is empty, current behavior applies (all properties included by default, unless the exclude checkbox is checked)
 * Otherwise, the field is interpreted as a comma-separated whitelist of properties to include, e.g. `AppName, Environment` (and `ExcludeAllProperties` is ignored, regardless of whether it's checked/unchecked)

While it will be slightly odd to have two fields to control property selection, it seems like a reasonable trade-off.

Thoughts? Anyone keen to investigate further/implement? Cheers!

**Comment by jglinsek** [comment]
👍 yeah, that would work for us.

**Comment by markduk** [comment]
Can this issue be marked as resolved now?
