### ISSUE TITLE
Exception detail is not set correctly

### ISSUE THREAD

**Issue by danpowell88** [bytenik/Seq.App.Slack#23]
Currently exception detail is being populated with 

> ExceptionDetail
> System.Collections.Generic.Dictionary`2[System.String,System.Object]

We are using 0.2.23
![untitled](https://user-images.githubusercontent.com/1100397/37379598-f9ec2df6-277f-11e8-83d4-1103e7e30ef7.png)

![untitled2](https://user-images.githubusercontent.com/1100397/37379648-40081f84-2780-11e8-8e3e-5008dfb28e5c.png)

**Comment by nblumhardt** [comment]
It looks like the `ToString()` here is the relevant LOC:

https://github.com/bytenik/Seq.App.Slack/blob/master/src/Seq.App.Slack/SlackReactor.cs#L127

Perhaps instead of calling `ToString()` directly on the property value, we should make a variant of `EventFormatting.FormatValue()` that does JSON conversion where appropriate, and use it here?

(Large blobs of JSON are going to be ugly to embed in Slack, however, so we might look at truncating it, as well...)

**Comment by rocklan** [comment]
I've attempted to fix this bug and it seems to be working ok. If a property is a generic Dictionary it will serialise it as JSON. You can also truncate it if you wish. In the first example the property "d" has been truncate and in the second it's not. 

![image](https://user-images.githubusercontent.com/2829865/43442119-618d0e58-94e0-11e8-9a5e-10cb7575a734.png)

**Comment by nblumhardt** [comment]
Fixed in #27
