### ISSUE TITLE
Add ability to see sample log events for alert sent to Slack

### ISSUE THREAD

**Issue by rastignacc** [bytenik/Seq.App.Slack#41]
It would be great to see few sample log events in Slack when Seq alert is triggered and then sent

**Comment by nblumhardt** [comment]
Thanks for the suggestion @rastignacc . I think this would have to be a Seq built-in feature, though there are some implementation challenges that have deterred us from pursuing it so far. For example, if the condition on an alert is `count(*) < 100` then it might be strange to include a selection of the 90 events that _were_ present, since the alert is really concerned with the missing 10.

Still very much aligned with other requests we've had, though, so it's a good data point for our future planning.
